### ISSUE TITLE
Criar - Função Somatório - Soma de Quadrados

### ISSUE THREAD

**Issue by EmersonFurlan** [EmersonFurlan/probest#21]

**Comment by lobaoff** [comment]
public static double calcularSomaQuadrados(double[] vetor) {
		double somaTotal;
		somaTotal = 0;
		double[] vetorAux = new double[vetor.length];
		for (int i = 0; i < vetor.length; i++) {
			vetorAux[i] += Math.pow(vetor[i], 2);

			System.out.print("|" + vetorAux[i] + "|");
			somaTotal += vetorAux[i];
		}
		System.out.println("A soma dos quadrados = " + somaTotal);
		return somaTotal;

**Comment by lobaoff** [comment]
Adicionei ao arquivo.
